<?php

/**
 * Textformatter Code Blocks
 * 
 * Textformatter for Markdown style code blocks. More about the syntax here:
 * https://help.github.com/articles/creating-and-highlighting-code-blocks/
 * 
 * @copyright 2018 Teppo Koivula
 * @license http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License, version 2
 */
class TextformatterCodeBlocks extends Textformatter {

    /**
     * Return module information.
     *
     * @return array Module info
     */
    public static function getModuleInfo() {
        return array(
            'title' => 'Code Blocks Textformatter',
            'summary' => 'Converts content within backticks into code blocks.',
            'version' => '0.2.0',
        );
    }

    /**
     * Format the given text string.
     *
     * @param string $str
     */
    public function format(&$str) {
        
        // use fast strpos check to make sure that $str contains backticks
        if (strpos($str, "`") === false) return;

        // wrap content within three backticks with code blocks, removing any
        // extraneous HTML line breaks (<br> tags) in the process
        if (strpos($str, "```") !== false) {
            if (preg_match_all('/(?:\<p(?:re)?(?: .*?)?\>)?[\r\n\s]*```(?:([a-z0-9-_]*)(?:(?:\<br\W*?\>)*[\r\n\s]*)?)(.*?)```[\r\n\s]*(?:\<\/p(?:re)?\>)?/si', $str, $matches)) {
                foreach ($matches[2] as $key => $value) {
                    $value = preg_replace('/\<br\W*\>/i', '', $value);
                    $value = '<pre class="code-block code-block--fenced"><code class="language-' . $matches[1][$key] . '">' . $value . '</code></pre>';
                    $str = str_replace($matches[0][$key], $value, $str);
                }
            }
        }
        
        // replace remaining double backticks with the HTML entity for a single
        // backtick, so that a single backtick can still be used within content
        // after being escaped with another single backtick
        $str = str_replace("``", "&#96;", $str);
        
        // wrap content wrapped with single backticks but not yet placed within
        // a code block with code blocks
        $str = preg_replace(
            '/\<code(?: .*?)?>.*\<\/code\>(*SKIP)(*F)|`(.*?)`/s',
            '<code class="code-block code-block--inline">$1</code>',
            $str
        );
        
    }

}
